[ARTS-48] view my sites
NDPH-ARTS/mts-trial-ui pull request #20
Opened 2021-03-12 10:41 UTC by mdp0

## Description
UI view of user's assigned trial sites

### Changes
- ARTS-48 - add sites view component and page

2021-03-15 11:40 UTC, darrengsmithson approved these changes

2021-03-17 11:21 UTC, eladiw commented on src/environments/environment.ts
> +  gatewayUrl: 'https://as-liza48a-sc-gateway-dev.azurewebsites.net/api',
this uri cant be hard coded

2021-03-17 11:22 UTC, eladiw requested changes
looks good. there is an hard coded uri which needs to be changed

2021-03-18 12:53 UTC, eladiw approved these changes

2021-03-18 13:56 UTC, merged